name: Integration Testing

on:
  push:
    branches: [ "main", "CI"]
  pull_request:
    branches: [ "main", "CI"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create .env file
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" > algonetAPI/.env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> algonetAPI/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> algonetAPI/.env
          echo "SS_USERNAME=${{ secrets.SS_USERNAME }}" >> algonetAPI/.env
          echo "SS_PASSWORD=${{ secrets.SS_PASSWORD }}" >> algonetAPI/.env
    
      # Set up Java 21 with the Temurin distribution
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'  # Use the Temurin distribution for Java 21

      # Change directory to a subfolder and run a Maven build
      - name: Run Maven build
        run: mvn clean install
        working-directory: ./algonetAPI

      # Change directory again to run tests in a different subfolder
      - name: Run tests
        run: mvn test -DTest=*IT
        working-directory: ./algonetAPI
